language: node_js

node_js:
  - "6"

# ensure we're using the container-based infrastructure
# see https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false

script:
  - npm test

cache:
  directories:
  - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  email: false
